### ISSUE TITLE
Hello, have you tried cifar10?

### ISSUE THREAD

**Issue by Cristina1213** [nguyenhongson1902/direct-training-snn#1]
Hello, have you tried cifar10?

**Comment by nguyenhongson1902** [comment]
> 

Thank you for taking care of this project. Unfortunately, for this codebase, I haven't because I didn't have enough resources (GPU, time, etc.). With that being said, you can try reading the code and adjusting it to the CIFAR-10 settings so as to see your desired results.

**Comment by Cristina1213** [comment]
Hello, thanks for your reply. I have tried cifar10, but when enlarging the time step, my device does not support it.
